### ISSUE TITLE
Geen tekst in de <ul>

### ISSUE THREAD

**Issue by suustenvoorde** [kimnikitaschijf/the-client-website#10]
Je kunt geen tekst in een <ul> toevoegen. Je kan daarvoor wel losse <li>'s gebruiken of een andere HTML tag.

https://github.com/kimnikitaschijf/the-client-website/blob/9efe62e8dd7339b2b3ce93602819882de4dbf13c/index.html#L107

**Comment by kimnikitaschijf** [comment]
Dit was nog van mijn vorige opdracht gekopieerd en geplakt. Heb het aangepast!
