### ISSUE TITLE
Gebruik eens een HTML validator, er zijn nog redelijk wat errors om op te lossen

### ISSUE THREAD

**Issue by suustenvoorde** [kimnikitaschijf/the-client-website#11]
Haal je HTML door de validator en los de errors op: https://validator.w3.org/

**Comment by kimnikitaschijf** [comment]
Heb ik opnieuw gedaan en heb al heel veel dingen kunnen veranderen. Van 42 naar nog maar 4 :)

**Comment by suustenvoorde** [comment]
Super! Dat maakt een goede basis om verder te gaan met de CSS
