### ISSUE TITLE
img in <ul>

### ISSUE THREAD

**Issue by lisagjh** [kimnikitaschijf/the-client-website#12]
https://github.com/kimnikitaschijf/the-client-website/blob/9efe62e8dd7339b2b3ce93602819882de4dbf13c/index.html#L22-L24

Waarom zet je de `<img>` in de `<ul>`, en niet gewoon er buiten in de header?

Een `<ul>` mag alleen `<li>` elementen als directe children hebben.

<img width="935" alt="Scherm­afbeelding 2024-10-04 om 11 34 32" src="https://github.com/user-attachments/assets/1fc9e774-64cf-4a86-a5b7-45617a1aefc8">

**Comment by kimnikitaschijf** [comment]
Heb het aangepast! Staat nu als volgt: 

[https://github.com/kimnikitaschijf/the-client-website/blob/main/index.html#L23-L24](url)
