### ISSUE TITLE
Gebruik een <ul> ipv een <div>

### ISSUE THREAD

**Issue by lisagjh** [kimnikitaschijf/the-client-website#13]
https://github.com/kimnikitaschijf/the-client-website/blob/9efe62e8dd7339b2b3ce93602819882de4dbf13c/index.html#L63-L73

Je hebt hier de list items in een div gezet, in plaats van een `<ul>`. Een list item moet altijd in een `<ul>` of een `<ol>` staan!

<img width="990" alt="Scherm­afbeelding 2024-10-04 om 11 35 55" src="https://github.com/user-attachments/assets/2782dcc8-d74b-4e3f-b9e2-f9f61dee99f8">

**Comment by kimnikitaschijf** [comment]
Opgelost!
