### ISSUE TITLE
Zet een <li> tag om de <img> in de <ul>

### ISSUE THREAD

**Issue by suustenvoorde** [kimnikitaschijf/the-client-website#5]
Je kunt geen andere tag dan een <li> in een <ul> plaatsen. Je kunt wel een andere tag in een <li> plaatsen. Daarnaast is het gebruikelijk om een logo klikbaar te maken. Zo kun je altijd terug naar de homepagina. 

https://github.com/kimnikitaschijf/the-client-website/blob/9efe62e8dd7339b2b3ce93602819882de4dbf13c/index.html#L23-L31

**Comment by kimnikitaschijf** [comment]
Heb het aangepast en het staat nu zo in mijn HTML:

[https://github.com/kimnikitaschijf/the-client-website/blob/3827a1c578591fcc465979027daa0d0dbbffa6e4/index.html#L22-L31](url)
