### ISSUE TITLE
Waar heb je deze <div> voor nodig?

### ISSUE THREAD

**Issue by suustenvoorde** [kimnikitaschijf/the-client-website#6]
Waar is deze <div> voor nodig?

https://github.com/kimnikitaschijf/the-client-website/blob/9efe62e8dd7339b2b3ce93602819882de4dbf13c/index.html#L38

**Comment by kimnikitaschijf** [comment]
Heb deze `div` inderdaad niet nodig. Heb hem weg gehaald!
