### ISSUE TITLE
Is het src of scr?

### ISSUE THREAD

**Issue by suustenvoorde** [kimnikitaschijf/the-client-website#9]
De <img> doet het niet wegens een typo. 

https://github.com/kimnikitaschijf/the-client-website/blob/9efe62e8dd7339b2b3ce93602819882de4dbf13c/index.html#L90

**Comment by kimnikitaschijf** [comment]
Typfoutje! Heb het opgelost overal :) `<li><img src="assets/green.jpg" alt="Groene bieb"></li>`
